openapi: 3.0.3
info:
  title: Cargo Pilot Analyzer API
  description: >-
    An API for uploading data to the online instance of Cargo Pilot
  version: 1.0.0
  contact:
    name: name
    email: mail@domain.com
servers:
  - url: https://cargo-pilot.de/api/analyzer
  - url: http://cp-analyzer:5000

#security:
#  - ApiKeyAuth: []

paths:
  
  /cluster/transport-items:
    post:
      tags:
        - "Cluster"
      description: Get clusters of transport items
      requestBody:
        description: "Cluster time range"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClusterItemsConfig"
      responses:
        "200":
          description: Successful operation

  /cluster/transport-items/statistics:
    post:
      tags:
        - "Cluster"
      description: Get clusters of transport items
      requestBody:
        description: "Cluster time range"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClusterItemsConfig"
      responses:
        "200":
          description: Successful operation

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    
    CompletedTrip:
      type: object
      properties:
        data_source:
          type: string
        origin:
          $ref: "#/components/schemas/Location"
        destination:
          $ref: "#/components/schemas/Location"
        cargo_item:
          $ref: "#/components/schemas/CargoItem"
        id:
          type: integer
          nullable: true
        customer:
          type: string
          nullable: true
        vehicle:
          $ref: "#/components/schemas/Vehicle"
        route_locations:
          type: array
          items:
            $ref: "#/components/schemas/Location"
          nullable: true

    Vehicle:
      type: object
      required:
        - type
        - stackable
        - max_loading_meter
        - max_weight
      properties:
        type: 
          type: string
        stackable:
          type: boolean
        max_loading_meter:
          type: number
          format: float
        max_weight:
          type: number
          format: float
        id:
          type: integer
          nullable: true

    ClusterItemsConfig:
      type: object
      required:
        - start_timestamp
        - end_timestamp
        - eps
        - min_samples
      properties:
        start_timestamp:
          type: integer
          format: int32
          example: 1689435073
        end_timestamp:
          type: integer
          format: int32
          example: 1689435073
        eps:
          type: number
          format: float
          example: 0.01
        min_samples:
          type: integer
          format: int32
          example: 5
        data_source:
          type: array
          example: ["Manual", "DB"]

    GeoLocation:
      type: object
      nullable: true
      properties:
        lat:
          type: number
          format: float
          nullable: true
        long:
          type: number
          format: float
          nullable: true
      example:
        lat: 12.345
        long: 67.890

    AdminLocation:
      type: object
      nullable: true
      properties:
        postal_code:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        country:
          type: string
          nullable: true
        street:
          type: string
          nullable: true
      example:
        postal_code: "12345"
        city: "City"
        country: "Country"
        street: "Street"

    CargoItem:
      type: object
      properties:
        load_carrier:
          type: boolean
        load_carrier_nestable:
          type: boolean
        loading_meter:
          type: number
          format: float
          nullable: true
        weight:
          type: number
          format: float
          nullable: true
      example:
        load_carrier: "Container"
        load_carrier_nestable: true
        loading_meter: 10.5
        weight: 500.0

    Location:
      type: object
      properties:
        id:
          type: integer
          nullable: true
        timestamp:
          type: integer
          nullable: true
        geo_location:
          nullable: true
          $ref: "#/components/schemas/GeoLocation"
          
        admin_location:
          $ref: "#/components/schemas/AdminLocation"
          nullable: true
      example:
        timestamp: 1706476224
        geo_location:
          lat: 12.345
          long: 67.890
        admin_location:
          postal_code: "12345"
          city: "City"
          country: "Country"
          street: "Street"

    CargoOrder:
      type: object
      properties:
        data_source:
          type: string
        origin:
          $ref: "#/components/schemas/Location"
        destination:
          $ref: "#/components/schemas/Location"
        cargo_item:
          $ref: "#/components/schemas/CargoItem"
        id:
          type: integer
          nullable: true
        customer:
          type: string
          nullable: true
        route_locations:
          type: array
          items:
            $ref: "#/components/schemas/Location"
          nullable: true
      example:
        data_source: "Company"
        origin:
          timestamp: 1706476224
          geo_location:
            lat: 12.345
            long: 67.890
          admin_location:
            postal_code: "12345"
            city: "City"
            country: "Country"
            street: "Street"
        destination:
          timestamp: "1706476224"
          id: "456"
          geo_location:
            lat: 23.456
            long: 45.678
          admin_location:
            postal_code: "67890"
            city: "Another City"
            country: "Another Country"
            street: "Another Street"
        cargo_item:
          load_carrier: "Container"
          load_carrier_nestable: true
          loading_meter: 10.5
          weight: 500.0
        id: "789"
        customer: "John Doe"
        route_locations:
          - timestamp: "1706476224"
            id: "101"
            geo_location:
              lat: 12.345
              long: 67.890
            admin_location:
              postal_code: "12345"
              city: "City"
              country: "Country"
              street: "Street"
          - timestamp: "1706476224"
            id: "102"
            geo_location:
              lat: 23.456
              long: 45.678
            admin_location:
              postal_code: "67890"
              city: "Another City"
              country: "Another Country"
              street: "Another Street"
